name: "release-notification-action"
description: "release-notification-action"

branding:
  icon: "bell"
  color: "white"

inputs:
  token:
    description: "GitHub token"
    required: true
  extractionStartPoint:
    description: "본문을 추출할 기점 해당 기점부터 최하단 정보를 전부 긁어옵니다. '== 릴리즈 내용 시작 =='"
    required: true
  extractionEndPoint:
    description: "해당 기점까지만 추출을 합니다. 만약 값이 없다면,extractionStartPoint 기점으로 모든 값을 긁어옵니다. '== 릴리즈 내용 종료 =='"
    required: false
  slackWebhookURL:
    description: "slack webhook url"
    required: true
  specificBranchPattern:
    description: "해당 브랜치에서만 액션에 대한 로직을 실행합니다. 만약 값을 넘기지 않는다면 모든 브랜치에서 실행됩니다. glob 패턴을 지원합니다 ex) 'release/*' / {main,develop,feature/*} "
    required: false
  specificDeployEnvironment:
    description: "배포 환경을 감지합니다. 만약 값이 없다면, 배포 환경을 감지하지 않습니다. glob 패턴을 지원합니다 ex) {Production,Preview}"
    required: false

runs:
  using: "node16"
  main: "dist/index.js"