name: "release-notification-action"
description: "release-notification-action"

branding:
  icon: "bell"
  color: "white"

inputs:
  token:
    description: "GitHub token"
    required: true
  extractionStartPoint:
    description: "본문을 추출할 기점 해당 기점부터 최하단 정보를 전부 긁어옵니다. '== 릴리즈 내용 시작 =='"
    required: true
  extractionEndPoint:
    description: "해당 기점까지만 추출을 합니다. 만약 값이 없다면,extractionStartPoint 기점으로 모든 값을 긁어옵니다. '== 릴리즈 내용 종료 =='"
    required: false
  slackWebhookURL:
    description: "slack webhook url"
    required: true
  projectConfig:
    description: "배포 알림 설정입니다. 자세한 내용은 readme를 참고해주세요."
    required: true

runs:
  using: "node16"
  main: "dist/index.js"