name: release-notification-action

on:
  [deployment_status]

jobs:
  release-notification-action:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: release-notification-action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          extractionStartPoint: '###### == 릴리즈 내용 시작 =='
          extractionEndPoint: '###### == 릴리즈 내용 종료 =='
          slackWebhookURL: ${{ secrets.SLACK_WEBHOOK_URL }}
          autoLinkConfig: >
            [
              {
                "targetURL": "https://www.google.com/search?q=<target>",
                "prefix": "DD-"
              },
              {
                "targetURL": "https://www.google.com/search?q=<target>",
                "prefix": "TEST-"
              }
            ]
          projectConfig: >
            [
              {
                "projectName": "Stock Web",
                "stage": "**",
                "triggerBranch": "main",
                "triggerFilePath": "**",
                "successReleaseTitle": "스톡 웹 DEV 클라이언트가 업데이트됐습니다.",
                "failedReleaseTitle": "스톡 웹 DEV 클라이언트가 배포에 실패했습니다."
              }
            ]