name: release-notification-action

on:
  [deployment_status]

jobs:
  release-notification-action:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: release-notification-action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          extractionStartPoint: '## == 릴리즈 내용 시작 =='
          extractionEndPoint: '## == 릴리즈 내용 종료 =='
          slackWebhookURL: ${{ secrets.SLACK_WEBHOOK_URL }}