name: release-notification-action

on:
  [deployment_status]

jobs:
  pr-action-body:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: release-notification-action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          extractionStartPoint: '## 리뷰 요약 정보'
          extractionEndPoint: '## 검토자가 알아야 할 사항'
          slackWebhookURL: ${{ secrets.SLACK_WEBHOOK_URL }}